newtopic_override_texts:
  type: list
  default: "webmethods-cloudstreams-connectors,webmethods_cloudstreams_connectors|feedback,feedback|staff,staff|knowledge-base,knowledge_base|knowledge-base/blog,knowledge_base_blog|knowledge-base/video,knowledge_base_video"
